; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = giga_r1_m7, giga_r1_m4

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
upload_protocol = dfu
build_flags = -I include
extra_scripts = pre:scripts/patch_hsmcpp_signature.py
build_src_filter = +<M7_app/>
lib_deps = 
	jonblack/arduino-fsm@^2.2.0
	igor-krechetov/hsmcpp@^1.0.4
	contrem/arduino-timer@^3.0.1

[env:giga_r1_m4]
platform = ststm32
board = giga_r1_m4
framework = arduino
monitor_speed = 115200
upload_protocol = dfu
build_flags = -I include
extra_scripts = pre:scripts/patch_hsmcpp_signature.py
build_src_filter = +<M4_app/>
lib_deps = 
	jonblack/arduino-fsm@^2.2.0
	igor-krechetov/hsmcpp@^1.0.4
	contrem/arduino-timer@^3.0.1
